LIST

INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Hemorrhagic Fever','Flavivirus',212);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Black Plague','Ebola',294);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Dengue Fever','HPV',24);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Rabies','Cylcospora',342);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Insomnia','Cylcospora',96);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Murdering Syndrome','Microsporidia',8);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Death Plague','E.coli',177);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('LG syndrome','HPV',295);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Procrastination','HPV',272);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Obesity','Ebola',30);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Being American','Marburg',10);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Alcoholism','Shigella',17);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Bipolar Disorder','Flavivirus',184);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Sociopathy','Clostridium',341);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Schizophrenia','HPV',147);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Chunnibyou','HPV',335);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Being a NEET','Marburg',39);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('ADHD','Marburg',281);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Having a waifu','Flavivirus',399);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Asthma','Microsporidia',66);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Arthritis','Microsporidia',398);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Bulimia','HPV',205);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Chickenpox','Clostridium',294);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Coma','Ebola',226);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Dystonia','Brucella',408);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Earache','Cylcospora',363);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Fibromyalgia','Clostridium',358);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Gallstones','Arenavirus',84);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Gastroenteritis','Brucella',262);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Gout','Cylcospora',367);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Lupus','Arenavirus',38);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Malaria','Flavivirus',374);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Mumps','Yersinia',394);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Norovirus','Cryptosporidium',215);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Nosebleed','Flavivirus',357);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Pneumonia','Influenza',212);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Psoriasis','Cylcospora',149);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Scabies','Cryptosporidium',183);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Shingles','Chlamydia',350);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Scoliosis','Influenza',162);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Suicide','Cylcospora',224);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Threadworms','Cryptosporidium',106);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Thirst','Clostridium',286);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Vampirism','Hantavirus',328);
INSERT INTO Illness(illness_name,pathogen,duration) VALUES ('Lycanthropy','Brucella',270);
