INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Hemorrhagic Fever','Heartburn');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Black Plague','Heartburn');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Dengue Fever','Paralysis');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Rabies','Cold');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Insomnia','Anemia');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Murdering Syndrome','Anxiety');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Death Plague','Pleurisy');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('LG syndrome','Delusions');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Procrastination','Rash');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Obesity','Catatonia');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Being American','Blisters');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Alcoholism','Palpitations');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Bipolar Disorder','Concussion');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Sociopathy','Paralysis');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Schizophrenia','Cellulitis');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Chunnibyou','Paranoia');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Being a NEET','Rash');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('ADHD','Cyanosis');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Having a waifu','Vomiting');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Asthma','Depression');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Arthritis','Delirium');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Bulimia','Anxiety');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Chickenpox','Cancer');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Coma','Hemolysis');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Dystonia','Cold');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Earache','Confusion');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Fibromyalgia','Hiccups');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Gallstones','Cancer');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Gastroenteritis','Depression');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Gout','Anxiety');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Lupus','Colitis');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Malaria','Confusion');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Mumps','Aphasia');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Norovirus','Aphasia');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Nosebleed','Cold');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Pneumonia','Cyanosis');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Psoriasis','Rash');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Scabies','Dysphagia');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Shingles','Cold');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Scoliosis','Confusion');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Suicide','Arrhythmia');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Threadworms','Cyanosis');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Thirst','Heartburn');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Vampirism','Confusion');
INSERT INTO Illness_has_symptom(illness_name,symptom) VALUES ('Lycanthropy','Rash');
