LIST

INSERT INTO Symptom(symptom,description) VALUES ('Anemia','Low Blood Sugar');
INSERT INTO Symptom(symptom,description) VALUES ('Anxiety','Fearfulness');
INSERT INTO Symptom(symptom,description) VALUES ('Aphasia','Voice Loss');
INSERT INTO Symptom(symptom,description) VALUES ('Arrhythmia','Irregular Heart Beat');
INSERT INTO Symptom(symptom,description) VALUES ('Blisters','Accumulation of liquid under skin');
INSERT INTO Symptom(symptom,description) VALUES ('Clotting','Potential arterial blockage');
INSERT INTO Symptom(symptom,description) VALUES ('Osteopenia','Bone loss');
INSERT INTO Symptom(symptom,description) VALUES ('Incontinence','Inability to control bowel movements');
INSERT INTO Symptom(symptom,description) VALUES ('Hives','Rash due to allergic reaction');
INSERT INTO Symptom(symptom,description) VALUES ('Inflammation','Natural response to pathogens');
INSERT INTO Symptom(symptom,description) VALUES ('Cancer','Mutagenic cells');
INSERT INTO Symptom(symptom,description) VALUES ('Catatonia','Sudden instances of sleep');
INSERT INTO Symptom(symptom,description) VALUES ('Cellulitis','Hardening of the skin');
INSERT INTO Symptom(symptom,description) VALUES ('Cold','General illness');
INSERT INTO Symptom(symptom,description) VALUES ('Cough','Attempts to expel pathogens');
INSERT INTO Symptom(symptom,description) VALUES ('Colitis','Colon inflammation');
INSERT INTO Symptom(symptom,description) VALUES ('Cyanosis','Blue hue due to lack of oxygen');
INSERT INTO Symptom(symptom,description) VALUES ('Confusion','Inability to comprehend the situation');
INSERT INTO Symptom(symptom,description) VALUES ('Concussion','Sudden impact to the cranium');
INSERT INTO Symptom(symptom,description) VALUES ('Delirium','Intense feelings of confusion');
INSERT INTO Symptom(symptom,description) VALUES ('Depression','Lack of neurotransmitters');
INSERT INTO Symptom(symptom,description) VALUES ('Diabetes','Loss of insulin');
INSERT INTO Symptom(symptom,description) VALUES ('Diarrhea','Potential dehydration');
INSERT INTO Symptom(symptom,description) VALUES ('Delusions','Feeling that the world is out to get you');
INSERT INTO Symptom(symptom,description) VALUES ('Drooling','Overactive salivary glands');
INSERT INTO Symptom(symptom,description) VALUES ('Dizziness','Mild instance of vertigo');
INSERT INTO Symptom(symptom,description) VALUES ('Dysphagia','Inability to chew');
INSERT INTO Symptom(symptom,description) VALUES ('Headache','Throbbing of the head');
INSERT INTO Symptom(symptom,description) VALUES ('Heartburn','Acid reflux in cardial area');
INSERT INTO Symptom(symptom,description) VALUES ('Hiccups','Attempts to expel air');
INSERT INTO Symptom(symptom,description) VALUES ('Hemolysis','Blood is exploding');
INSERT INTO Symptom(symptom,description) VALUES ('Hyperventilation','Inability to properly calm down');
INSERT INTO Symptom(symptom,description) VALUES ('Jaundice','Liver failure');
INSERT INTO Symptom(symptom,description) VALUES ('Vertigo','Seeing the world upside down');
INSERT INTO Symptom(symptom,description) VALUES ('Vomiting','Expulsion of stomach contents');
INSERT INTO Symptom(symptom,description) VALUES ('Rash','Skin problems');
INSERT INTO Symptom(symptom,description) VALUES ('Palpitations','Heart beating rapidly');
INSERT INTO Symptom(symptom,description) VALUES ('Paralysis','Inability to move');
INSERT INTO Symptom(symptom,description) VALUES ('Paranoia','They’re coming for you');
INSERT INTO Symptom(symptom,description) VALUES ('Pleurisy','Weakening of the pleural cavity');
INSERT INTO Symptom(symptom,description) VALUES ('Weakness','Get swoll');
